/*
 * fsm_ui.c
 *
 * Created: 4/27/2021 11:31:59 PM
 * Author : Akm Islam
 */ 


//***************************************************************************
//
// File Name            : "main.c"
// Title                : Design Task 2
// Date                 : 4/29/21
// Version              : 1.0
// Target MCU           : AVR128DB48
// Target Hardware      ; MCP23S17
// Author               : Akm Islam
// DESCRIPTION
//						 This program measures the time and temperature,
//						 which is then displayed on the LCD. It also features
//						 a basic UI using Tera Term and the USART3 module.
//						 This allows operators to change the time settings.
// Warnings             :
// Restrictions         : none
// Algorithms           : none
// References           :
//
// Revision History     : Initial version
//
//
//**************************************************************************


#define F_CPU 4000000
#include <avr/io.h>
#include <util/delay.h>
#include <avr/interrupt.h>
#include <stdio.h>

#include "ADC.h"
#include "DOG_LCD.h"
#include "DS1306_RTC_drivers.h"
#include "RS232.h"
#include "fsm_ui.h"



//***************************************************************************
//
// Function Name        : "ISR for PORTC"
// Date                 : 4/29/21
// Version              : 1.0
// Target MCU           : AVR128
// Target Hardware      ; AVR128DB48
// Author               : Akm Islam
// DESCRIPTION			This ISR services the interrupt generated by the 1Hz
//						output to keep updating the time and temperature.
//
// Warnings             : none
// Restrictions         : none
// Algorithms           : none
// References           : none
//
// Revision History     : Initial version
//
//**************************************************************************
ISR(PORTC_PORT_vect)
{
	uint8_t dummy;
	uint8_t digit[4];
	cli();	//Disable interrupts.

	block_read_RTC(RTC_time_date_read, Read_Time_Date_Start, 7);	//Read time and date.
	
	digit[0] = RTC_time_date_read[0];
	digit[1] = RTC_time_date_read[1];
	digit[2] = RTC_time_date_read[2];
	digit[3] = RTC_time_date_read[3];
	
	sprintf(dsp_buff1, "Time %1d%1d:%1d%1d:%1d%1d",  (RTC_time_date_read[2] >> 4) & (0x03), RTC_time_date_read[2] & (0x0F) , (RTC_time_date_read[1] >> 4) & (0x0F), RTC_time_date_read[1] & (0x0F) , (RTC_time_date_read[0] >> 4) & (0x0F), RTC_time_date_read[0] & (0x0F));
	
	adc_conversion();	//Compute result from ADC to temperature.
	
	if (ADC_bin < 0x334)
	//		{
	sprintf(dsp_buff2, "Temp = -%d%d%d.%d%cC", celsius[3], celsius[2], celsius[1], celsius[0], 0xDF);
	//		}
	else
	//		{
	sprintf(dsp_buff2, "Temp = %d%d%d.%d%cC  ", celsius[3], celsius[2], celsius[1], celsius[0], 0xDF);		//Display each decimal place of temperature in Celsius.
	//		}
	//	sprintf(dsp_buff3, "                ");
	
	//	dummy = read_RTC(READ_Alarm0_Register);		//Clear IRQF0
	
	update_lcd_dog();	//Update LCD.
	
	VPORTC.INTFLAGS = PIN2_bm;	//Clear PC2 interrupt flag.
	
	sei();	//Enable interrupts.
}


//***************************************************************************
//
// Function Name        : "ISR for USART3"
// Date                 : 4/29/21
// Version              : 1.0
// Target MCU           : AVR128
// Target Hardware      ; AVR128DB48
// Author               : Akm Islam
// DESCRIPTION			This ISR services the interrupt generated by the
//						the USART3 receiver. New inputs are used to look
//						into the FSM tables.
//
// Warnings             : none
// Restrictions         : none
// Algorithms           : none
// References           : none
//
// Revision History     : Initial version
//
//**************************************************************************
ISR(USART3_RXC_vect)
{
	cli();	//Disable interrupts.
	
	SPI_rtc_ds1306_config();
	
	volatile unsigned char char_received;	//Declare local variable.
	
	char_received = USART3.RXDATAL;		//Read received character.
	USART_sw_write(char_received);
	USART_sw_write(10);		//Print CR.
	USART_sw_write(13);		//Print LF.
	
	if (char_received == 's') fsm(present_state, s);
	else if (char_received == 'h') fsm(present_state, h);
	else if (char_received == 'm') fsm(present_state, m);
	else if (char_received == 'c') fsm(present_state, c);
	else if ((char_received >= '0') && (char_received <= '9'))
		{
			digit_val = char_received & 0x0F;
			fsm(present_state, digit);
		}
	else if (char_received == 0x0D) fsm(present_state, enter);
	else fsm(present_state, char_received);
	

	
//	USART3.TXDATAL = USART3.RXDATAL;	//Clear RX register
//	USART3.STATUS = USART_RXCIF_bm;		//Clear RX interrupt flag.
	
	sei();	//Enable interrupts.
}


//***************************************************************************
//
// Function Name        : "main"
// Date                 : 4/29/21
// Version              : 1.0
// Target MCU           : AVR128
// Target Hardware      ; AVR128DB48
// Author               : Akm Islam
// DESCRIPTION			This main function configures the required modules.
//						The superloop is left empty.
//
// Warnings             : none
// Restrictions         : none
// Algorithms           : none
// References           : none
//
// Revision History     : Initial version
//
//**************************************************************************
int main(void)
{
    //Start
    init_lcd_dog();		//Initialize LCD.
    init_adc();			//Initialize ADC.
    configure_DS1306();	//Initialize RTC.
	init_usart();		//Initialize USART3.
    sei();
	
	present_state = idle;
		
	
	//Main loop
    while (1) 
    {
		asm volatile ("nop");	//Empty main loop.
    }	//End main loop.
	
	return 0;
}

